# Laboratorio 3

Juan Pablo Rodas Martinez

carnet 23007125

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Parte #1 - Numpy

### 1)

In [20]:
a = np.full(1000,True)

print(f'El tamaño en bytes de un array de 100 elementos de tipo booleano es de {a.nbytes} bytes')

El tamaño en bytes de un array de 100 elementos de tipo booleano es de 1000 bytes


### 2)

In [42]:
b =  np.arange(2,101,2)
b = b[::-1]

print(b[-10:])

[20 18 16 14 12 10  8  6  4  2]


### 3)

In [101]:
c = np.array([[2,4,5,6],
             [0,3,7,4],
             [8,8,5,2],
             [1,5,6,1]])
print(f'dada la matriz {c}\n')

print(f'seleccionar: {c[1]}\n')
print(f'seleccionar: \n{c[0:3:2][0::1,0:3:2]}')

dada la matriz [[2 4 5 6]
 [0 3 7 4]
 [8 8 5 2]
 [1 5 6 1]]

seleccionar: [0 3 7 4]

seleccionar: 
[[2 5]
 [8 5]]


### 4)

In [104]:
a = np.array([1,4,2,7])
b = np.array([1,3,2,9])

c = a-b
print(f'La madia aritmetica de (a-b) es = {c.mean()}')

La madia aritmetica de (a-b) es = -0.25


### 5)

In [142]:
coordenadas = np.array([[1.33,4.5],[30.0,10.7],[70.2,0.5]])
coordenadas=np.append(coordenadas,[[37.1,-3.6]],axis=0)
print(coordenadas)
print(f'Las dimensiones del array son: {coordenadas.shape}')

[[ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]
 [37.1  -3.6 ]]
Las dimensiones del array son: (4, 2)


### 6)

In [149]:
newCoord=coordenadas.transpose()
newCoord=np.append(newCoord,[[10.8],[3.0]],axis=1)
newCoord=np.append(newCoord,[[35.8],[12.0]],axis=1)
print(f'El nuevo array es: \n{newCoord}')

El nuevo array es: 
[[ 1.33 30.   70.2  37.1  10.8  35.8 ]
 [ 4.5  10.7   0.5  -3.6   3.   12.  ]]
